UPDATED 06

diff --git a/testmail06 b/testmail06
--- a/testmail06
+++ b/testmail06
@@ -2,46 +2,41 @@ pipeline {
     agent any
 
     stages {
-        stage('Parallel steps') {
-            parallel {
-                stage('parallel stage 1 of 2 ') {
-                    steps {
-                        script {
-                            try {
-                                sh "cd /opt/ansible; set -e; ansible-playbook  -i ./list  ping-setup.yml "
-                                //stage1of2.result = "SUCCESS"
-                            } catch (e) {
-                                stage1of2.result = "FAILURE"
-                                echo('detected failure: stage 1 of 2 failed')
-                                echo 'Hi something failed !'
-                                emailext body: '${DEFAULT_CONTENT}',
-                                recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
-                                subject: '${DEFAULT_SUBJECT}'
-                                throw(e)
-                            }
-                        }
+        stage('stage 1 of 2 ') {
+            steps {
+                script {
+                    try {
+                        sh "cd /opt/ansible; set -e; ansible-playbook  -i ./list  ping-setup.yml "
+                        //stage1of2.result = "SUCCESS"
+                    } catch (e) {
+                        stage1of2.result = "FAILURE"
+                        echo('detected failure: stage 1 of 2 failed')
+                        echo 'Hi something failed !'
+                        emailext body: '${DEFAULT_CONTENT}',
+                        recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
+                        subject: '${DEFAULT_SUBJECT}'
+                        throw(e)
                     }
                 }
-                stage('parallel stage 2 of 2') {
-                    steps {
-                        script {
-                            try {
-                                //sh "cd /opt/ansible; set -e; ansible-playbook  -i ./list  ping-setup.yml "
-                                sh "cd /opt/ansible"
-                                //stage2of2.result = "SUCCESS"
-                            } catch (e) {
-                                echo('detected failure: stage 2 of 2 failed')
-                                stage2of2.result = "FAILURE"
-                                throw(e)
-                            }
-                        }
-                    }
-                }
-
-
             }
         }
-  
+        stage('stage 2 of 2') {
+            steps {
+                script {
+                    try {
+                        //sh "cd /opt/ansible; set -e; ansible-playbook  -i ./list  ping-setup.yml "
+                        sh "cd /opt/ansible"
+                        //stage2of2.result = "SUCCESS"
+                    } catch (e) {
+                        echo('detected failure: stage 2 of 2 failed')
+                        stage2of2.result = "FAILURE"
+                        throw(e)
+                    }
+                        }
+                    }
+                }
+
+ 
         stage('Final steps') {
             steps {
                 script {
@@ -49,10 +44,10 @@ pipeline {
                     //if (stage1of2.result == "FAILURE") or (stage2of2.result == "FAILURE")
                     //    {echo('detected failure: either stage failed') }
                     //else
-                        {echo('detected Success')}
-                           }
-				   }
+                    
+                    }
 				}
+		}
     }
 }
 
